export const environments = {
	FIREBASE_CONFIG_API_KEY: import.meta.env.VITE_FIREBASE_CONFIG_API_KEY,
	FIREBASE_CONFIG_AUTH_DOMAIN: import.meta.env.VITE_FIREBASE_CONFIG_AUTH_DOMAIN,
	FIREBASE_CONFIG_PROJECT_ID: import.meta.env.VITE_FIREBASE_CONFIG_PROJECT_ID,
	FIREBASE_CONFIG_STORAGE_BUCKET: import.meta.env.VITE_FIREBASE_CONFIG_STORAGE_BUCKET,
	FIREBASE_CONFIG_MESSAGING_SENDER_ID: import.meta.env.VITE_FIREBASE_CONFIG_MESSAGING_SENDER_ID,
	FIREBASE_CONFIG_APP_ID: import.meta.env.VITE_FIREBASE_CONFIG_APP_ID,
}
